import type { Agent } from "@/types/agent";

/**
 * The Agent Bureau registry — the single source of truth for which agents
 * exist and what they are permitted to do.
 *
 * SUPERVISION CONTRACT: every agent prepares and proposes; outward actions are
 * listed in `blockedActions` until a human approves them via the approval queue.
 * No entry here should imply autonomous execution of risky real-world actions.
 */
export const AGENTS: Agent[] = [
  {
    id: "chief-of-staff",
    name: "Chief of Staff",
    role: "Zentrale Intelligenz & Koordination",
    description:
      "Priorisiert die Arbeit, erstellt das tägliche Briefing, koordiniert die übrigen Agenten und legt Entscheidungen zur Freigabe vor.",
    status: "active",
    riskLevel: "low",
    requiresApproval: true,
    capabilities: [
      { id: "prioritize", label: "Priorisierung", description: "Bewertet, was heute Aufmerksamkeit braucht." },
      { id: "brief", label: "Tägliches Briefing", description: "Fasst Lage, Risiken und nächste Schritte zusammen." },
      { id: "coordinate", label: "Koordination", description: "Verteilt Aufgaben an die passenden Agenten." },
    ],
    allowedActions: ["Briefing erstellen", "Prioritäten vorschlagen", "Aufgaben zur Freigabe vorlegen"],
    blockedActions: ["E-Mails senden", "Zahlungen auslösen", "Daten löschen"],
    connectedSystems: ["Tasks", "Projects", "Approvals"],
    supportedOperatingStages: ["audit", "diagnose", "design", "manual_delivery", "install", "maintain"],
    auditPainsSolved: ["Unklare Prioritäten", "Fehlende Übersicht"],
    playbooks: ["pb-daily-briefing", "pb-missed-inquiry", "pb-shadow-ai-policy"],
    businessOutcomes: ["Klarheit", "Bessere Entscheidungen", "Weniger Chaos"],
    lastActivity: "2026-05-29T07:55:00Z",
    nextRecommendedAction: "Tagesbriefing um 08:00 zur Durchsicht bereitstellen.",
  },
  {
    id: "lead-agent",
    name: "Lead Agent",
    role: "Lead-Recherche & Qualifizierung",
    description:
      "Recherchiert Firmen, findet Kontakte, reichert Datensätze an und qualifiziert eingehende Anfragen.",
    status: "proposing",
    riskLevel: "medium",
    requiresApproval: true,
    capabilities: [
      { id: "research", label: "Firmen-Recherche", description: "Sammelt öffentliche Informationen zu Interessenten." },
      { id: "enrich", label: "Anreicherung", description: "Ergänzt fehlende Felder in Kontaktdatensätzen." },
      { id: "qualify", label: "Qualifizierung", description: "Bewertet Eignung und Dringlichkeit." },
    ],
    allowedActions: ["Lead recherchieren", "Datensatz anreichern", "Qualifizierungs-Score vorschlagen"],
    blockedActions: ["Kontakt direkt anschreiben", "Daten an Dritte exportieren"],
    connectedSystems: ["Leads", "Contacts", "Research"],
    supportedOperatingStages: ["audit", "design", "manual_delivery"],
    auditPainsSolved: ["Lead-Leckage", "Schwaches Lead-Tracking"],
    playbooks: ["pb-lead-followup"],
    businessOutcomes: ["Mehr qualifizierte Chancen", "Weniger verlorene Leads"],
    lastActivity: "2026-05-29T07:40:00Z",
    nextRecommendedAction: "Neue Audit-Anfrage aus Essen qualifizieren.",
  },
  {
    id: "research-agent",
    name: "Research Agent",
    role: "Markt- & Wettbewerbsbeobachtung",
    description:
      "Beobachtet Markt, Wettbewerb und Branchensignale und meldet relevante Gelegenheiten.",
    status: "idle",
    riskLevel: "low",
    requiresApproval: false,
    capabilities: [
      { id: "scan", label: "Markt-Scan", description: "Verfolgt Entwicklungen in definierten Themenfeldern." },
      { id: "summarize", label: "Zusammenfassung", description: "Verdichtet Funde zu kurzen Briefs." },
    ],
    allowedActions: ["Markt-Scan durchführen", "Brief zusammenfassen"],
    blockedActions: ["Externe Inhalte veröffentlichen"],
    connectedSystems: ["Research", "Memory"],
    supportedOperatingStages: ["audit", "diagnose"],
    auditPainsSolved: ["Fehlende Marktübersicht"],
    playbooks: ["pb-meeting-prep"],
    businessOutcomes: ["Frühe Chancen-Erkennung", "Informierte Entscheidungen"],
    lastActivity: "2026-05-28T16:20:00Z",
    nextRecommendedAction: "Wöchentlichen Wettbewerbs-Brief vorbereiten.",
  },
  {
    id: "crm-agent",
    name: "CRM Agent",
    role: "Beziehungspflege & Follow-up",
    description:
      "Verfolgt Deals, erinnert an Follow-ups und hält Kontaktdaten aktuell.",
    status: "proposing",
    riskLevel: "medium",
    requiresApproval: true,
    capabilities: [
      { id: "followup", label: "Follow-up-Tracking", description: "Erkennt fällige Nachfassaktionen." },
      { id: "hygiene", label: "Datenpflege", description: "Markiert veraltete oder doppelte Datensätze." },
    ],
    allowedActions: ["Follow-up vorbereiten", "Datensatz-Korrektur vorschlagen"],
    blockedActions: ["Nachricht an Kunden senden", "Deal-Status final ändern"],
    connectedSystems: ["Contacts", "Leads", "Tasks"],
    supportedOperatingStages: ["manual_delivery", "systemize"],
    auditPainsSolved: ["Verpasste Follow-ups", "Schwaches Lead-Tracking"],
    playbooks: ["pb-crm-cleanup", "pb-waiting-room"],
    businessOutcomes: ["Verlässliches Follow-through", "Gepflegte Beziehungen"],
    lastActivity: "2026-05-29T06:30:00Z",
    nextRecommendedAction: "3 überfällige Follow-ups zur Freigabe vorlegen.",
  },
  {
    id: "calendar-agent",
    name: "Calendar Agent",
    role: "Termine & Erinnerungen",
    description:
      "Schlägt Termine vor, erinnert an Meetings und hält den Kalender aufgeräumt.",
    status: "idle",
    riskLevel: "medium",
    requiresApproval: true,
    capabilities: [
      { id: "schedule", label: "Terminvorschlag", description: "Findet passende Zeitfenster." },
      { id: "remind", label: "Erinnerung", description: "Weist auf anstehende Meetings hin." },
    ],
    allowedActions: ["Terminvorschlag erstellen", "Erinnerung vorbereiten"],
    blockedActions: ["Einladung versenden", "Termin im Kalender Dritter buchen"],
    connectedSystems: ["Calendar", "Tasks"],
    supportedOperatingStages: ["manual_delivery", "systemize"],
    auditPainsSolved: ["Langsame Antworten", "Unklare Prioritäten"],
    playbooks: ["pb-meeting-prep"],
    businessOutcomes: ["Aufgeräumter Kalender", "Vorbereitete Termine"],
    lastActivity: "2026-05-29T07:10:00Z",
    nextRecommendedAction: "Slot für Audit-Gespräch vorschlagen.",
  },
  {
    id: "content-agent",
    name: "Content Agent",
    role: "Content-Planung & Entwürfe",
    description:
      "Plant Content, erstellt Entwürfe und bereitet Kampagnen vor — zur Prüfung, nicht zur Veröffentlichung.",
    status: "idle",
    riskLevel: "medium",
    requiresApproval: true,
    capabilities: [
      { id: "plan", label: "Planung", description: "Skizziert Themen und Zeitplan." },
      { id: "draft", label: "Entwurf", description: "Erstellt Roh-Entwürfe zur Prüfung." },
    ],
    allowedActions: ["Content-Plan erstellen", "Entwurf vorbereiten"],
    blockedActions: ["Beitrag veröffentlichen", "Newsletter versenden"],
    connectedSystems: ["Content", "Memory"],
    supportedOperatingStages: ["systemize"],
    auditPainsSolved: ["Manuelle Verwaltung", "Content nur einmal genutzt"],
    playbooks: ["pb-content-repurpose"],
    businessOutcomes: ["Mehr Reichweite", "Konsistente Kommunikation"],
    lastActivity: "2026-05-28T14:05:00Z",
    nextRecommendedAction: "Entwurf für Fallstudien-Post zur Prüfung vorlegen.",
  },
  {
    id: "operations-agent",
    name: "Operations Agent",
    role: "Projekt- & Aufgabenkoordination",
    description:
      "Verfolgt Projekte, Aufgaben und Deadlines und meldet Blockaden frühzeitig.",
    status: "active",
    riskLevel: "low",
    requiresApproval: false,
    capabilities: [
      { id: "track", label: "Tracking", description: "Behält Fortschritt und Deadlines im Blick." },
      { id: "flag", label: "Eskalation", description: "Markiert Risiken und Blockaden." },
    ],
    allowedActions: ["Projektstatus berichten", "Risiko markieren"],
    blockedActions: ["Aufgaben Dritter umverteilen ohne Freigabe"],
    connectedSystems: ["Projects", "Tasks"],
    supportedOperatingStages: ["audit", "diagnose", "systemize", "maintain"],
    auditPainsSolved: ["Verstreute Aufgaben", "Fehlende Übersicht", "Reporting-Verzug"],
    playbooks: ["pb-overdue-task"],
    businessOutcomes: ["Prozess-Sichtbarkeit", "Eingehaltene Deadlines"],
    lastActivity: "2026-05-29T07:50:00Z",
    nextRecommendedAction: "Blockiertes Projekt 'Website-Migration' eskalieren.",
  },
  {
    id: "document-agent",
    name: "Document Agent",
    role: "Dokumente & Aufbereitung",
    description:
      "Erstellt und strukturiert Dokumente wie Angebote, Berichte und Zusammenfassungen — zur Freigabe.",
    status: "idle",
    riskLevel: "medium",
    requiresApproval: true,
    capabilities: [
      { id: "compose", label: "Erstellung", description: "Entwirft strukturierte Dokumente." },
      { id: "extract", label: "Extraktion", description: "Fasst Inhalte aus Quelldokumenten zusammen." },
    ],
    allowedActions: ["Angebot entwerfen", "Bericht zusammenfassen"],
    blockedActions: ["Dokument extern verschicken", "Rechnung final ausstellen"],
    connectedSystems: ["Memory", "Projects"],
    supportedOperatingStages: ["systemize", "install"],
    auditPainsSolved: ["Dokumenten-Chaos", "Manuelle Verwaltung"],
    playbooks: ["pb-document-summary"],
    businessOutcomes: ["Klare nächste Aktion pro Dokument", "Weniger übersehene Fristen"],
    lastActivity: "2026-05-28T11:25:00Z",
    nextRecommendedAction: "Angebotsentwurf für neue Anfrage vorbereiten.",
  },
  {
    id: "follow-up-agent",
    name: "Follow-Up Agent",
    role: "Nachverfolgung & Wiedervorlage",
    description:
      "Stellt sicher, dass keine Chance und kein Versprechen untergeht — bereitet Wiedervorlagen vor.",
    status: "proposing",
    riskLevel: "high",
    requiresApproval: true,
    capabilities: [
      { id: "detect", label: "Erkennung", description: "Findet offene Zusagen und stille Threads." },
      { id: "prepare", label: "Vorbereitung", description: "Entwirft die nächste Nachfassaktion." },
    ],
    allowedActions: ["Wiedervorlage erkennen", "Nachfass-Entwurf vorbereiten"],
    blockedActions: ["Nachricht eigenständig senden", "Mehrfach-Versand ohne Freigabe"],
    connectedSystems: ["Contacts", "Tasks", "Approvals"],
    supportedOperatingStages: ["manual_delivery", "systemize"],
    auditPainsSolved: ["Verpasste Follow-ups", "Langsame Antworten", "Lead-Leckage"],
    playbooks: ["pb-lead-followup", "pb-missed-inquiry", "pb-waiting-room"],
    businessOutcomes: ["Keine verlorene Chance", "Verlässliches Follow-through"],
    lastActivity: "2026-05-29T06:50:00Z",
    nextRecommendedAction: "5 stille Threads zur Wiedervorlage vorlegen.",
  },
];

export function getAgentById(id: string): Agent | undefined {
  return AGENTS.find((a) => a.id === id);
}
