import type { Playbook } from "@/types/playbook";

// Reusable agent playbooks — the repeatable delivery system that turns manual
// concierge work into installable workflows. Every playbook ends in a human
// review step before any execute/log (supervision contract).
const review = (id: string, n: number, label: string, lifecycle: Playbook["steps"][number]["lifecycle"]) => ({
  id,
  order: n,
  label,
  lifecycle,
});

export const PLAYBOOKS: Playbook[] = [
  {
    id: "pb-lead-followup",
    title: "Lead-Follow-up",
    businessPain: "Leads kommen rein, aber niemand fasst nach.",
    trigger: "Neuer qualifizierter Lead ohne Reaktion seit 24h.",
    responsibleAgents: ["lead-agent", "follow-up-agent"],
    steps: [
      review("s1", 1, "Stillen Lead erkennen", "observe"),
      review("s2", 2, "Kontext zusammenstellen", "prepare"),
      review("s3", 3, "Nachfass-Entwurf vorschlagen", "propose"),
      review("s4", 4, "Freigabe einholen", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Reaktivierter Lead mit nächstem Schritt.",
    operatingStage: "manual_delivery",
    reusableTemplate: true,
  },
  {
    id: "pb-missed-inquiry",
    title: "Verpasste-Anfrage-Rettung",
    businessPain: "Anfragen nach Feierabend gehen unter.",
    trigger: "Eingehende Anfrage ohne Erfassung.",
    responsibleAgents: ["chief-of-staff", "follow-up-agent"],
    steps: [
      review("s1", 1, "Anfrage erfassen", "observe"),
      review("s2", 2, "Dringlichkeit einschätzen", "prepare"),
      review("s3", 3, "Antwort vorbereiten", "propose"),
      review("s4", 4, "Freigabe einholen", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Keine Anfrage bleibt unbeantwortet.",
    operatingStage: "manual_delivery",
    reusableTemplate: true,
  },
  {
    id: "pb-daily-briefing",
    title: "Tägliches Briefing",
    businessPain: "Kein klarer Tagesstart, Prioritäten unklar.",
    trigger: "Jeden Morgen um 08:00.",
    responsibleAgents: ["chief-of-staff"],
    steps: [
      review("s1", 1, "Lage beobachten", "observe"),
      review("s2", 2, "Prioritäten verdichten", "prepare"),
      review("s3", 3, "Briefing vorlegen", "propose"),
      review("s4", 4, "Durchsicht durch Owner", "human_review"),
    ],
    approvalRequired: false,
    expectedOutcome: "Klarer, priorisierter Start in den Tag.",
    operatingStage: "systemize",
    reusableTemplate: true,
  },
  {
    id: "pb-crm-cleanup",
    title: "CRM-Bereinigung",
    businessPain: "Veraltete, doppelte Kontaktdaten.",
    trigger: "Monatlicher Datenhygiene-Lauf.",
    responsibleAgents: ["crm-agent"],
    steps: [
      review("s1", 1, "Auffälligkeiten erkennen", "observe"),
      review("s2", 2, "Korrekturen vorbereiten", "prepare"),
      review("s3", 3, "Änderungen vorschlagen", "propose"),
      review("s4", 4, "Freigabe einholen", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Saubere, verlässliche Kontaktbasis.",
    operatingStage: "systemize",
    reusableTemplate: true,
  },
  {
    id: "pb-meeting-prep",
    title: "Meeting-Vorbereitung",
    businessPain: "Unvorbereitet in Termine gehen.",
    trigger: "Termin in den nächsten 24h.",
    responsibleAgents: ["calendar-agent", "research-agent"],
    steps: [
      review("s1", 1, "Termin erkennen", "observe"),
      review("s2", 2, "Kontext recherchieren", "prepare"),
      review("s3", 3, "Briefing-Karte vorschlagen", "propose"),
      review("s4", 4, "Durchsicht", "human_review"),
    ],
    approvalRequired: false,
    expectedOutcome: "Vorbereitet in jedes Gespräch.",
    operatingStage: "systemize",
    reusableTemplate: true,
  },
  {
    id: "pb-document-summary",
    title: "Dokument-Zusammenfassung",
    businessPain: "Wichtiges in langen Dokumenten übersehen.",
    trigger: "Neues Dokument im Intake.",
    responsibleAgents: ["document-agent"],
    steps: [
      review("s1", 1, "Dokument erkennen", "observe"),
      review("s2", 2, "Kernpunkte extrahieren", "prepare"),
      review("s3", 3, "Zusammenfassung + Aktion vorschlagen", "propose"),
      review("s4", 4, "Freigabe einholen", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Klare nächste Aktion pro Dokument.",
    operatingStage: "systemize",
    reusableTemplate: true,
  },
  {
    id: "pb-content-repurpose",
    title: "Content-Wiederverwertung",
    businessPain: "Guter Content wird nur einmal genutzt.",
    trigger: "Neuer Beitrag oder Fallstudie.",
    responsibleAgents: ["content-agent"],
    steps: [
      review("s1", 1, "Quelle erkennen", "observe"),
      review("s2", 2, "Varianten entwerfen", "prepare"),
      review("s3", 3, "Entwürfe vorschlagen", "propose"),
      review("s4", 4, "Freigabe vor Veröffentlichung", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Mehr Reichweite aus vorhandenem Content.",
    operatingStage: "systemize",
    reusableTemplate: true,
  },
  {
    id: "pb-overdue-task",
    title: "Überfällige-Aufgaben-Rettung",
    businessPain: "Aufgaben werden überfällig und blockieren.",
    trigger: "Aufgabe überschreitet Fälligkeit.",
    responsibleAgents: ["operations-agent"],
    steps: [
      review("s1", 1, "Überfälligkeit erkennen", "observe"),
      review("s2", 2, "Ursache/Blocker prüfen", "prepare"),
      review("s3", 3, "Eskalation vorschlagen", "propose"),
      review("s4", 4, "Durchsicht", "human_review"),
    ],
    approvalRequired: false,
    expectedOutcome: "Blockaden werden früh sichtbar.",
    operatingStage: "manual_delivery",
    reusableTemplate: true,
  },
  {
    id: "pb-shadow-ai-policy",
    title: "Shadow-AI-Policy",
    businessPain: "Team nutzt unkontrolliert KI-Tools.",
    trigger: "Governance-Review oder neue Tool-Meldung.",
    responsibleAgents: ["chief-of-staff"],
    steps: [
      review("s1", 1, "Tool-Nutzung erfassen", "observe"),
      review("s2", 2, "Risiko einordnen", "prepare"),
      review("s3", 3, "Policy-Maßnahme vorschlagen", "propose"),
      review("s4", 4, "Freigabe durch Owner", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Klare, durchgesetzte KI-Richtlinie.",
    operatingStage: "diagnose",
    reusableTemplate: true,
  },
  {
    id: "pb-waiting-room",
    title: "Kunden-Warteraum",
    businessPain: "Kunden warten auf Antwort und springen ab.",
    trigger: "Kunde wartet länger als Schwellwert.",
    responsibleAgents: ["follow-up-agent", "crm-agent"],
    steps: [
      review("s1", 1, "Wartende erkennen", "observe"),
      review("s2", 2, "Antwort vorbereiten", "prepare"),
      review("s3", 3, "Nächste Aktion vorschlagen", "propose"),
      review("s4", 4, "Freigabe einholen", "human_review"),
    ],
    approvalRequired: true,
    expectedOutcome: "Niemand wartet zu lange.",
    operatingStage: "manual_delivery",
    reusableTemplate: true,
  },
];

export function getPlaybookById(id: string) {
  return PLAYBOOKS.find((p) => p.id === id);
}
